typography_spectrum: 0.14335401891730726
color:
  brandStrength: 0.6881139911711216
  lightness: 0.6690753796137869
  saturation: 0.47422466706484556
  rhythmicContrast: 0.23809452215209603
  brandColors:
    - '#FFFFFF'
    - '#FFFF01'
    - '#214EFF'
    - '#7894FF'
    - '#5B6341'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/087bb835-4d56-4176-86c3-71f2a5802c80.jpg
layout_spectrum: 0.9040570012293756
author:
  name: Emil Zakirov Saidovich
  email: 4uniquemind@gmail.com
  url: 'https://twitter.com/ZakirovEmil'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/66605148-dd6d-4262-b2fd-54feda3a2fd1.jpg
name: mapget.ru
navigation:
  - name: МАП ГЭТ
    id: d8fbdfcc-b7b2-4cfe-8cac-cf29a615e46e
    type: content
  - name: Руководство
    id: 508a39b5-bd1c-4000-8736-4eeeab185688
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c94d8ee9-233f-4a94-be05-4ae806a55918.jpg
title: МАПГЭТ
description: '  Международная ассоциация    предприятий городского   электрического транспорта'
